### ISSUE TITLE
How to download the fantasic spectral video in Fig. 3 

### ISSUE THREAD

**Issue by ErqiHuang** [mengziyi64/TSA-Net#3]
The spectral video your presented on the page is so funny, could you share it?

**Comment by mengziyi64** [comment]
Video data has been added.

https://pan.baidu.com/s/1k0khhPytcbKTb0G5NsaFCw
8n9x










At 2021-11-03 15:12:51, "ErqiHuang" ***@***.***> wrote:

The spectral video your presented on the page is so funny, could you share it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ErqiHuang** [comment]
> 8n9x

Thank you for you sharing!
